PostgresqlDemo.WebUI/Areas/Admin/Controllers/ProfileController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using PostgresqlDemo.WebCore.Extensions;
using PostgresqlDemo.WebCore.Modules.Profile.Models;
using PostgresqlDemo.WebCore.Modules.Profile.Services;
using PostgresqlDemo.WebUI.Controllers.Base;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;

namespace PostgresqlDemo.WebUI.Areas.Admin.Controllers
{
    public class ProfileController : AuthorizedController
    {
        private readonly IProfileService _service;

        public ProfileController(IProfileService service)
        {
            _service = service;
        }

        public async Task<ActionResult> PersonalInfo()
        {
            return View(await _service.GetPersonalInfo());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> PersonalInfo(PersonalInfoModel model)
        {
            var result = await _service.UpdatePersonalInfo(model);

            if (result.Succeeded)
            {
                return View(model).WithSuccess("Update successfully");
            }

            ModelState.AddIdentityResultErrors(result);
            return View(model);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> ChangePassword(ChangePasswordModel model)
        {
            var result = await _service.ChangePassword(model);

            if (result.Succeeded)
            {
                return RedirectToAction("ChangePassword").WithSuccess("Update successfully");
            }

            ModelState.AddIdentityResultErrors(result);
            return View(model);
        }

    }
}

PostgresqlDemo.WebUI/Controllers/HomeController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using PostgresqlDemo.WebCore.Modules.Posts.Services;
using PostgresqlDemo.WebUI.Controllers.Base;

namespace PostgresqlDemo.WebUI.Controllers
{
    public class HomeController : BaseController
    {
        private readonly IPostService _postService;

        public HomeController(IPostService postService)
        {
            _postService = postService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetPost()
        {
            return Json(await _postService.GetAll().ToListAsync());
        }
    }
}

PostgresqlDemo.WebUI/Views/Home/Index.cshtml
@using PostgresqlDemo.WebUI.Infrastructure.Extensions
@{
    ViewBag.Title = "Home";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            @{
                if (Request.IsAuthenticated)
                {
                    <div class="dropdown profile-element row">

                        <div class="col-md-1" style="width: 4% !important;padding-bottom: 5px">
                            @{
                                var avatarClass = "";
                                if (!string.IsNullOrEmpty(CurrentUser.Info.Avatar))
                                {
                                    avatarClass = "image-profile";
                                }

                                <span class="group-avatar @avatarClass" style="margin-top: -15px">
                                    <a class="btn btn-primary btn-circle letter-avatar" href="@Url.Action("PersonalInfo", "Profile", new {area = "Customer"})">
                                        <span>@CurrentUser.Info.UserName[0].ToString().ToUpper()</span>
                                    </a>
                                    <a class="btn btn-circle full-height image-avatar" href="@Url.Action("PersonalInfo", "Profile", new {area = "Customer"})">
                                        <img alt="avatar" class="img-circle img-md" src="@CurrentUser.Info.Avatar" />
                                    </a>
                                </span>
                            }
                        </div>

                        <div class="col-md-11">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="text-muted text-xs block" style="color: white">@(string.Join(" ", CurrentUser.Roles)) <b class="caret"></b></span>
                                </span>
                            </a>

                            <ul class="dropdown-menu m-t-xs">
                                <li><a href="@Url.Action("PersonalInfo", "Profile", new {area = "Admin"})">Manage Content</a></li>
                                <li><a href="@Url.Action("Logout", "Account", new {area = ""})">Log out</a></li>
                            </ul>
                        </div>
                    </div>

                }
                else
                {
                    <a class="btn btn-primary" href="@Url.Action("Login", "Account")">
                        <i class="fa fa-sign-in"></i> LOGIN
                    </a>
                    <a class="btn btn-default" href="@Url.Action("Register", "Account")">
                        <i class="fa fa-user-plus"></i> SIGN UP
                    </a>
                }
            }

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>BLOG</h5>
                </div>
                <div class="wrapper wrapper-content animated fadeInRight" id="ajax-post-content" style="padding-left: 0; padding-right: 0">
                    @Html.Spinner()
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @ViewHelper.RenderPageScript("home/home")
}