PostgresqlDemo.WebUI/Areas/Admin/Controllers/FileManagerController.cs
using System;
using System.Web.Mvc;
using PostgresqlDemo.WebCore.Modules.FileManager.Models;
using PostgresqlDemo.WebCore.Services;
using PostgresqlDemo.WebUI.Controllers.Base;
using Core.Web.Mvc.Ajax;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace PostgresqlDemo.WebUI.Areas.Admin.Controllers
{
    public class FileManagerController : AuthorizedController
    {
        private readonly IManageFileService _service;

        public FileManagerController(IManageFileService service)
        {
            _service = service;
        }

        public ActionResult Index(string targetId)
        {
            return View(new UploadedFileModel
            {
                TargetId = targetId
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public ActionResult Index(UploadedFileModel model)
        {
            try
            {
                _service.Upload(model);
                return RedirectToAction("Index", new { targetId = model.TargetId })
                                .WithSuccess("Upload successfully");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }
            return View(model);
        }

        public ActionResult ListView_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_service.GetList().ToDataSourceResult(request));
        }

        [HttpPost]
        public ActionResult DeleteFile(FileModel model)
        {
            try
            {
                _service.DeleteThumbnail(model.Name);
                return Json(AjaxResult.Success().ToResult());
            }
            catch (Exception ex)
            {
                return Json(AjaxResult.Error().WithException(ex).ToResult());
            }
        }
    }
}

PostgresqlDemo.WebUI/Views/Shared/EditorTemplates/App/ActivationStatus.cshtml
@using PostgresqlDemo.DataAccess.Enums
@using Core.Extensions
@using Core.Web.MetadataModel.Common
@model EActivationStatus?

@(Html.Kendo().DropDownListFor(m => m)
          .DataValueField("Value")
          .DataTextField("Text")
          .BindTo(typeof(EActivationStatus).ToEnumPairInt())
          .HtmlAttributes(Html.ModelHtmlAttributes())
          .Deferred(ViewData.ModelMetadata.Options().Deferred)
)

PostgresqlDemo.WebUI/Views/Shared/EditorTemplates/App/FilePicker.cshtml
@using Core.Web.MetadataModel.Common

@{
    var name = Html.NameForModel().ToString();
    var url = Url.Action("Index", "FileManager", new { targetId = name });
    var htmlAttributes = Html
            .ModelHtmlAttributes()
            .AttrIfNotNull("readonly", "");
}

<div class="input-group file-picker">
    <a class="input-group-addon btn btn-default file-picker-preview">
        <i class="fa fa-photo"></i>
    </a>
    @(Html.Kendo().TextBoxFor(m => m)
              .HtmlAttributes(htmlAttributes)
              .Deferred())


    <a class="input-group-addon btn btn-default" onclick="KendoHelper.showPopup('@url')">
        <i class="fa fa-upload"></i> Select
    </a>
    @if (!ViewData.ModelMetadata.IsRequired())
    {
        <a class="input-group-addon btn btn-default file-picker-clear">
            <i class="fa fa-remove"></i>
        </a>
    }

</div>

PostgresqlDemo.WebUI/Views/Shared/EditorTemplates/App/LanguagePicker.cshtml
@using PostgresqlDemo.WebCore.Services
@using Core.Web.MetadataModel.Common
@model string

@{
    var languages = GetService<ILanguageService>().GetAll();
}

@(Html.Kendo().DropDownListFor(m => m)
      .OptionLabel("Select language...")
      .DataValueField("Name")
      .DataTextField("DisplayName")
      .Filter(FilterType.Contains)
      .HtmlAttributes(Html.ModelHtmlAttributes())
      .BindTo(languages)
      .Deferred(ViewData.ModelMetadata.Options().Deferred)
)

PostgresqlDemo.WebUI/Views/Shared/EditorTemplates/App/UserCategories.cshtml
@using PostgresqlDemo.WebCore.Modules.Categories.Services
@using Core.Web.MetadataModel.Common
@{
    var categories = GetService<ICategoryService>().GetList().Result;
}
@(Html.Kendo().DropDownListFor(m => m)
    .OptionLabel("Select category...")
    .DataValueField("Id")
    .DataTextField("Text")
    .Template("<span style='padding-left: #=Padding#px'>#= Text#<span>")
    .BindTo(categories)
    .HtmlAttributes(Html.ModelHtmlAttributes().AddStyle("min-width:250px"))
    .Deferred()
)

PostgresqlDemo.WebUI/Views/Shared/EditorTemplates/App/UserLanguages.cshtml
@using PostgresqlDemo.WebCore.Services
@using Core.Web.MetadataModel.Common

@model string

@{
    var languages = GetService<IUserLanguage>().GetAll();
    var deferred = ViewData.ModelMetadata.Options().Deferred;
    var optionLabel = ViewData.ModelMetadata.Options().OptionLabel ?? "Select language...";
}

@(Html.Kendo().DropDownListFor(m => m)
    .OptionLabel(optionLabel)
    .DataValueField("Name")
    .DataTextField("DisplayName")
    .HtmlAttributes(Html.ModelHtmlAttributes().AddStyle(string.Format("min-width:{0}", deferred ? "250px" : "100%")))
    .BindTo(languages)
    .Deferred(ViewData.ModelMetadata.Options().Deferred)
)