PostgresqlDemo.WebUI/Areas/Admin/Controllers/ManagePostController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core.Web.Mvc.Alerts;
using Core.Web.Mvc.Filters;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using PostgresqlDemo.WebCore.Modules.Posts.Models;
using PostgresqlDemo.WebCore.Modules.Posts.Services;
using PostgresqlDemo.WebUI.Controllers.Base;

namespace PostgresqlDemo.WebUI.Areas.Admin.Controllers
{
    public class ManagePostController : HostAuthorizedController
    {
        private readonly IPostService _service;

        public ManagePostController(IPostService service)
        {
            _service = service;
        }

        public ActionResult Grid_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_service.GetAll().ToDataSourceResult(request));
        }

        [HttpPost]
        public Task<ActionResult> Grid_Destroy([DataSourceRequest] DataSourceRequest request, PostModel model)
        {
            return ExecuteGridActionAsync(request, model, () => _service.Delete(model.Id));
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new PostModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Create(PostModel model)
        {
            try
            {
                await _service.Create(model);
                return RedirectToAction("Index").WithSuccess("Tạo thành công");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            return View(await _service.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateModel]
        public async Task<ActionResult> Edit(PostModel model)
        {
            try
            {
                await _service.Update(model);
                return View(model).WithSuccess("Cập nhật thành công");
            }
            catch (Exception ex)
            {
                HandleError(ex);
            }
            return View(model);
        }
    }
}

PostgresqlDemo.WebUI/Areas/Admin/Views/ManagePost/Create.cshtml
@using Core.Web.Extensions
@model PostgresqlDemo.WebCore.Modules.Posts.Models.PostModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Thông tin bài đăng</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Tạo
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index", "ManagePost", new { area = "Admin" })">
                            <i class="fa fa-arrow-left"></i> Trở lại
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        Validator.default();
    </script>
}

PostgresqlDemo.WebUI/Areas/Admin/Views/ManagePost/Edit.cshtml
@using Core.Web.Extensions
@model PostgresqlDemo.WebCore.Modules.Posts.Models.PostModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Thông tin bài đăng</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.FormPost())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ErrorSummary()

                        @Html.EditorForModel("Form")

                        <button type="submit" class="ladda-button btn btn-primary">
                            <i class="fa fa-save"></i> Cập nhật
                        </button>

                        <a class="btn btn-default" href="@Url.Action("Index", "ManagePost", new { area = "Admin" })">
                            <i class="fa fa-arrow-left"></i> Trở lại
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        Validator.default();
    </script>
}

PostgresqlDemo.WebUI/Areas/Admin/Views/ManagePost/Index.cshtml
@using Core.Web.Kendo
@using Kendo.Mvc.UI
@using PostgresqlDemo.WebCore.Modules.Posts.Models

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Danh sách Bài đăng</h5>
                    <div class="ibox-tools">
                        <div class="buttons">
                            <a class="btn btn-primary btn-sm" href="@Url.Action("Create", "ManagePost")">
                                <i class="fa fa-plus"></i> Thêm mới
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    @(Html.Kendo().Grid<PostModel>()
                                .DefaultSettings()
                                .Columns(columns =>
                                {
                                    columns.Bound(p => p.Title).ClientTemplate("<a href='/Admin/ManagePost/Edit/#:Id#'>#:Title#</a>");
                                    columns.Command(x =>
                                    {
                                        x.Destroy().Text("Xóa");
                                    }).Width(50);
                                })
                                  .DataSource(dataSource => dataSource
                                      .Ajax()
                                      .DefaultSettings()
                                      .Model(model =>
                                      {
                                          model.Id(p => p.Id);
                                      })
                                      .Read(read => read.Action("Grid_Read", "ManagePost"))
                                      .Destroy(destroy => destroy.Action("Grid_Destroy", "ManagePost"))
                                  ).Deferred()
                    )
                </div>
            </div>
        </div>
    </div>
</div>